(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 800,
	height: 800,
	fps: 30,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



// stage content:
(lib.aunit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#222222").ss(1,1,1).p("Ego0A55QgBAvgQAwQgPAxhVAzQgFgGhfAGQggARhEgRQg7gygpAyQhkguhkAuQhcg8hsA8Qg8AngoA9QgtAEg3gEQgyAngygnQgHgoAHg8QhQhRgUgTQgyhHgygdQgZgpAZg7QALiBgLirQgDiwADjgQgKgVAKhPQgKiSAKiaQgKkPAKjlQAUimBQiGQgKiSAKiaQAoiDgoipQA3hvAti9QgcjOAcjCQg3i1gth3QgFhgAFhnQgthag3huQAZhpgZhfQgBmQABmQQgKjmAKkOQgPgeAPhGQhUoWBUo2QgjhQAjh4QgDifADiNQAGjcgGi0QAAgyAAgyQCSgRCaARQCCAtBGA3QDCgODOAOQBGgUCCAUQB4gYC0AYQCZhOCTgWQCgAPCMgPQB4AUC0gUQAeAZBGgZQC5AeDXgeQBzAeC5geQB9AeCvgeQCWAkCWgkQDNAKDBgKQC5AKDXgKQCCAOCqgOQCMgFCgAFQBpgKBfAKQCQgPCcAPQCfgbCNAbQBKgZAaAZQCjAECJgEQCaAACSAAQAsgFA4AFQC4gPDYAPQAzgYAxAYQAxgyAzgyQC3A0DZAwQAQAtBUgtQAiAyBCAyQgigXhCAXQA7AjApBBQgFBZAFBvQgVBkAVBkQgPCXAPCVQg0CigwCKQgfDHAfDJQAOAPgOBVQA2BaAuBuQgVAZAVBLQAHDDgHDNQgBCcABCQQgVBuAVBaQgNDSANC+QgBB4ABBQQgBClABCHQgBC+ABDRQgLBeALBqQgsFeg4FeQAgBtggBbQATBygTBWQAPB4gPBQQAsCtgsB/QAYBAgYAkQgOC4AOB0QgVBeAVBqQgkAdAkBHQhBF3gjFFQgjERAWDnQgqALgtgPQhCgGgiAGQimgBiGABQkeACjWgCQiXATiVgTQhgAWhogWQi1Adh3gdQhvAnhZgnQiXBDiVAhQkxgEknAEQjsgKkIAKQhfgphpg7QieAliMglQhagQhuAQQmehKmCgaQivAdh9gdQhRAih3giQgFAThfgTQgZAOhLgOQhuAJhagJQiHgGhBAGQjOgpixg2QgJgDgIgCQgFg4AFgsQASA0gBA1gEArRgMfQA4CIg4CkQAOBfgOBpQgQBzAQBVQguCtg2B+QAdAxgdAzEAptAJYQA4gvAsg1QApBlgpBjQgzgfgxAfQg9g9gngnQA0huAwAKQAnA7gnApgEA6sA9AQAFAwAIAwQAJAsgJA4QBGgUAehQQgzgHgxhdQgHACgGACgAlJH0QAKiNgKifQAjhqBBjBQgKhzAKi5QBRijATjtQAjBfBBBpQAAB9AACvQBnC5BfDWQAACLAAChQA7CNApCfQAKgzgKgxQAyhgAyhoQAojiA8iuQA3j0Atj/QA4hyAsi6Am5nlQgEBjAQBXQgoCMAoCfQgyBtAyBbQgoCjAYCeQAGgLAKgKAm2oSQgCAXgBAWQAGgHAGgHQgGgRgDgOQgNg8AWgJQgGAjgDAigAwFq7QhLBagZBuQgPDDAPDNQgZCPAZCcQAUB8BQBMQgPBFAPAfQAoAJA8gJQBLhHB9iBQAtgpA3g7QAjiXBBiUQgeg8AegoQAIi6BQhkAQtq7QgLDFALDLQgyA8gyCMQAKBLgKB8QgeByAeBWQhSDpgSCnAbppXQAnCqgnCCQA2CMAuCfQgpBeApBqQgaDWAaC6QgLBKALAaAbppXQCLgoChAoQC5g1DXgvAVZnzQDNhYDDgMEgi1gK6QhdhLhrgaQh4gehQAeQjVhHhXCrQhfAygFAyQhLCHgZBBQgPCCAPBGQgzDeAzCxQgZBtAZBbQA3AxAtAzQBpATBfgTQBuAiBagiQCMhCA8iGQBzhCgPiGQBkiLAAigQABgDABgDQgBA1gBA1QA1DvAvEEEgi1gK7IAAABQAGD2gED3QBAi6AijQQgwg5g0gqEghRgJXQgeg8hGgoQAjhfgjgFQgPg/AOgjQglBUAmByAm9IJQAGAnAKAoQgoglAYgqg");
	this.shape.setTransform(403.1,400);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(404.8,389,796.6,822);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;